name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Checks
        run: |
          go install github.com/alexkohler/prealloc@v1.0.0
          prealloc -set_exit_status ./...
          go install github.com/alexkohler/nakedret@b2c0146
          nakedret -set_exit_status ./...
          go install github.com/ashanbrown/makezero@v1.1.1
          makezero -set_exit_status ./...

      - name: Test
        run: go test -v ./...
